### ISSUE TITLE
Enhancement tips

### ISSUE THREAD

**Issue by teilorr** [Kotov584/Telegant#1]
Hey! you didn't defined any contribution guideline, so I'm writing this issue without any specifications in mind.

So, the thing that is annoying me the most is that you aren't consistent with the naming convention on your code. You defined `sendMessage` using a case that is not appropriate to methods. Instead, you should use `snake_case` here. I understand that in the API, it's in `PascalCase`, however, you're writing a _python_ program, therefore you should follow the _python_ convention for naming.

You should probably annotate your code, since it is a library. This way the user can understand more easily what is happening with their code. A typechecker that i use is `pyright`, it's fast 🙂

Also, run a formatter on your code before uploading it to github. For automating this, you probably want to use github actions. I personally recommend black as a formatter.

**Comment by Kotov584** [comment]
Hello!
Thank you for your ideas of how I can improve my library as it is important for me and community :)
I will take your suggestions and will improve it within time 
Thank you!
